proc sql;
	CREATE TABLE WORK.IQV AS 	
	SELECT P.TYPE, ROUND((K * ((100*100) - SUM((P/TOT*100)*(P/TOT*100)))) / ((100*100) * (K-1)), 0.01) AS IQV
	FROM (
	  SELECT 'COUNTRY' AS TYPE, COUNT(*) AS P FROM DM.RAW GROUP BY COUNTRY 
	  UNION
	  SELECT 'GENDER', COUNT(*) AS P FROM DM.RAW GROUP BY GENDER 
	  UNION
	  SELECT 'JOB', COUNT(*) AS P FROM DM.RAW GROUP BY JOB 
	  UNION
	  SELECT 'JOBTYPE', COUNT(*) AS P FROM DM.RAW GROUP BY JOBTYPE 
	  UNION
	  SELECT 'MARITAL_STATUS', COUNT(*) AS P FROM DM.RAW GROUP BY MARITAL_STATUS 
	  UNION
	  SELECT 'QUALIFICATION', COUNT(*) AS P FROM DM.RAW GROUP BY QUALIFICATION
	  UNION
	  SELECT 'RACE', COUNT(*) AS P FROM DM.RAW GROUP BY RACE 
	  UNION
	  SELECT 'RELATIONSHIP_STATUS' AS TYPE, COUNT(*) AS P FROM DM.RAW GROUP BY RELATIONSHIP_STATUS 
	  UNION
	  SELECT 'SALARY', COUNT(*) AS P FROM DM.RAW GROUP BY SALARY 
  	) P
 	INNER JOIN ( 
	  SELECT 'COUNTRY' AS TYPE, COUNT(DISTINCT COUNTRY) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'GENDER' AS TYPE, COUNT(DISTINCT GENDER) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'JOB' AS TYPE, COUNT(DISTINCT JOB) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'JOBTYPE' AS TYPE, COUNT(DISTINCT JOBTYPE) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'MARITAL_STATUS' AS TYPE, COUNT(DISTINCT MARITAL_STATUS) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'QUALIFICATION' AS TYPE, COUNT(DISTINCT QUALIFICATION) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'RACE' AS TYPE, COUNT(DISTINCT RACE) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'RELATIONSHIP_STATUS' AS TYPE, COUNT(DISTINCT RELATIONSHIP_STATUS) AS K, COUNT(*) AS TOT FROM DM.RAW
	  UNION
	  SELECT 'SALARY' AS TYPE, COUNT(DISTINCT SALARY) AS K, COUNT(*) AS TOT FROM DM.RAW
	  ) K 
	  ON P.TYPE = K.TYPE
GROUP BY P.TYPE
;
run;

proc print data=work.iqv;
run;
